[build]
  command = "npm run build"  # This builds your React app
  publish = "build"          # The output directory for your React app

[functions]
  node_bundler = "esbuild"
  directory = "netlify-functions"  # Your Python serverless functions will live here

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/main"
  status = 200

[[redirects]]
  from = "/denoise-demo/"
  to = "/.netlify/functions/main/denoise-demo/"
  status = 200

[[redirects]]
  from = "/static/uploaded_images/*"
  to = "/.netlify/functions/main/static/uploaded_images/:splat"
  status = 200

[[redirects]]
  from = "/static/cleaned_images/*"
  to = "/.netlify/functions/main/static/cleaned_images/:splat"
  status = 200