[build]
  base = "frontend"
  command = "npm run build"
  publish = "frontend/build"

# If you have serverless functions in netlify-functions/
[functions]
  directory = "netlify-functions"

# Redirect API requests to your backend if needed
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
